# Generated by Django 5.2.6 on 2025-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_gamesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='potion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.potion'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sword',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.sword'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
